<?php
namespace AppBundle\Repository;

use AppBundle\Entity\ProduitCommande;

/**
 * ProduitCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitCommandeRepository extends AbstractEnitityRepository
{

    public function montant()
    {
        $qb = $this->createQueryBuilder('t');
        return $qb
            ->select('sum(t.prix * t.qte)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * Native Sql 
     * select produit_id, sum(qte) from produit_commande group by produit_id Order by sum(qte) desc;
     */
    public function topSales($limit=5)
    {
        return $this->createQueryBuilder('pc')
            ->select(['prd.libelle','SUM(pc.qte) as qte'])
            ->join('pc.produit', 'prd')
            ->groupBy('pc.produit')
            ->orderBy('qte','DESC')
            ->getQuery()
            ->setMaxResults($limit)
            ->getArrayResult();

    }
}
